/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 park.glb 
Author: matousekfoto (https://sketchfab.com/matousekfoto)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skatepark-17e32c89b5574d48b10f06a57d2500df
Title: Skatepark
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Park(props) {
  const { nodes, materials } = useGLTF('/park.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.029, -0.01, 0]} rotation={[-Math.PI / 2, 0.014, 0]} scale={0.2}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.skatepark_skatepark_u1_v1_0.geometry} material={materials.skatepark_u1_v1} />
            <mesh geometry={nodes.skatepark_skatepark_u1_v1_0_1.geometry} material={materials.skatepark_u1_v1} />
            <mesh geometry={nodes.skatepark_skatepark_u2_v1_0.geometry} material={materials.skatepark_u2_v1} />
            <mesh geometry={nodes.skatepark_skatepark_u2_v1_0_1.geometry} material={materials.skatepark_u2_v1} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/park.glb')
