/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 skt.gltf 
*/

import React, { useRef, useState } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { MeshStandardMaterial } from 'three';

export default function Skate(props) {
  const { nodes, materials } = useGLTF('/skate/skt.gltf');
  const [texture, setTexture] = useState(materials.deckm.map);
  const tTexture = useTexture('/skate/textures/tabla3.png');
  console.log(materials.deckm);

  const handleClick = () => {
    console.log('click');
    setTexture(tTexture);
  };

  const deckMaterial = new MeshStandardMaterial();
  deckMaterial.map = texture;
  deckMaterial.name = 'deckm';

  return (
    <group {...props} dispose={null} scale={[0.15, 0.15, 0.15]} position={[-0.25, 1, 0.18]} rotation={[0, -Math.PI / 2, 0]}>
      <group rotation={[Math.PI / 2, 0.019, Math.PI]}>
        <group position={[0, -0.079, 0.623]} scale={[1.172, 1, 1]}>
          <mesh geometry={nodes.deck.geometry} material={deckMaterial} onClick={handleClick}/>
          <mesh geometry={nodes.grid.geometry} material={materials.gridm} />
        </group>
        <mesh geometry={nodes.bearing_back_left_1_0.geometry} material={materials['Bearing.001']} position={[0.92, 2.325, -0.091]} rotation={[0, 1.571, 0]} scale={[0.139, 0.139, 0.152]} />
        <mesh geometry={nodes.bearing_back_left_2_0.geometry} material={materials['Bearing.001']} position={[0.69, 2.325, -0.091]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={[0.139, 0.139, 0.152]} />
        <mesh geometry={nodes.bearing_back_right_1_0.geometry} material={materials['Bearing.001']} position={[-0.929, 2.326, -0.091]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={[0.139, 0.139, 0.152]} />
        <mesh geometry={nodes.bearing_back_right_2_0.geometry} material={materials['Bearing.001']} position={[-0.699, 2.326, -0.091]} rotation={[0, 1.571, 0]} scale={[0.139, 0.139, 0.152]} />
        <mesh geometry={nodes.bearing_front_left_1_0.geometry} material={materials['Bearing.001']} position={[0.922, -2.433, -0.091]} rotation={[0, 1.571, 0]} scale={[0.139, 0.139, 0.152]} />
        <mesh geometry={nodes.bearing_front_left_2_0.geometry} material={materials['Bearing.001']} position={[0.692, -2.433, -0.091]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={[0.139, 0.139, 0.152]} />
        <mesh geometry={nodes.bearing_front_right_1_0.geometry} material={materials['Bearing.001']} position={[-0.927, -2.432, -0.091]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={[0.139, 0.139, 0.152]} />
        <mesh geometry={nodes.bearing_front_right_2_0.geometry} material={materials['Bearing.001']} position={[-0.697, -2.432, -0.091]} rotation={[0, 1.571, 0]} scale={[0.139, 0.139, 0.152]} />
        <mesh geometry={nodes.Truck_back_0.geometry} material={materials['truck.001']} position={[0.002, 2.199, 0.317]} rotation={[-0.025, 0, 0]} scale={[1.09, 1, 1]} />
        <mesh geometry={nodes.Truck_front_0.geometry} material={materials['truck.001']} position={[-0.01, -2.306, 0.317]} rotation={[0.025, 0, -Math.PI]} scale={[1.09, 1, 1]} />
        <mesh geometry={nodes.wheel_back_left_0.geometry} material={materials['wheel.001']} position={[0.809, 2.327, -0.091]} rotation={[0, 1.571, 0]} scale={[1, 1, 1.091]} />
        <mesh geometry={nodes.wheel_back_right_0.geometry} material={materials['wheel.001']} position={[-0.819, 2.325, -0.091]} rotation={[-1.455, -Math.PI / 2, 0]} scale={[1, 1, 1.091]} />
        <mesh geometry={nodes.wheel_front_left_0.geometry} material={materials['wheel.001']} position={[0.811, -2.432, -0.091]} rotation={[-1.48, 1.57, 0]} scale={[1, 1, 1.091]} />
        <mesh geometry={nodes.wheel_front_right_0.geometry} material={materials['wheel.001']} position={[-0.817, -2.434, -0.091]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={[1, 1, 1.091]} />
      </group>
    </group>
  )
}

useGLTF.preload('/skate/skt.gltf')
